### ISSUE TITLE
The UNSUNG Vietnam War Mod

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#154]
Because i know we were looking for a Vietnam mod...

__Description:__
Welcome to Nam soldier! You’ll soon be stalking Charlie in the thick jungles of Vietnam, your CAR-15 in hand, wondering whether he’s above, below or behind you. Watch out for traps, snipers up in the trees, or spider-holes and tunnels while securing villages to win Hearts and Minds. Fly long range bombing and CAS missions from the Gulf of Tonkin. Target the NVA SAM batteries from afar, or deliver napalm into the treeline to support your hard-pressed comrades.

The Unsung team, working on an authentic Vietnam-era mod pack since OFP brings you realistic jungle fighting, hand-to-hand combat and fully 3-dimensional warfare in this immersive mod pack for Arma 3.

__Link:__ http://www.armaholic.com/page.php?id=29948
__Size:__ 1400MB

**Comment by ShiFoo** [comment]
If the quality is good, we could replace an existing vietnam-like map with this.

**Comment by Fourjays** [comment]
I gave it a quick look last night. Quality wise it looks good, but the size seems rather large for what is there.

I'm really concerned about the developer's attitude though. On the forum post they say it is an alpha, but "don't want any bug reports". So if there are bugs it'll be us that has to deal with them.

**Comment by Fourjays** [comment]
Done a check and decompressed it is 2.90GB.

Vests don't appear to be 1.54 compatible either so not much point even considering it right now.

**Comment by abelarno** [comment]
>Let me make this perfectly clear once and for all... The team has stated many times in past posts that the unsung will NOT be specially configured to work with other mods.. The team is hard pressed currently making all our A2 content work correctly in A3. We simply do not have the time or resources to make it compatible with every other mod out there. So if it works with other mods good... if not too bad. Simple as that .

Mod might not be playing nice with our whole modpack, and issue's with other mods might arise in the future that won't have any soft of priority from the devs.

We should keep this in mind, even if the mod works fine with our pack right now.

Will test the mod later today.

**Comment by abelarno** [comment]
Most important issue for now: 
Vests are still not updated to 1.54 standard.
Mod is not compatibale with ACE3.

I see no reason to implement this mod.

**Comment by Fourjays** [comment]
Rejected in the meeting on 03/01/2016 due to poor compatibility with our modset.
